// <auto-generated />
using System;
using AgendaEstudos.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AgendaEstudos.Migrations
{
    [DbContext(typeof(AgendaEstudosDbContext))]
    partial class AgendaEstudosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AgendaEstudos.Models.Tarefa", b =>
                {
                    b.Property<long>("TarefaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Bibligrafia")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CriadaEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2020, 8, 21, 18, 48, 36, 477, DateTimeKind.Local).AddTicks(3337));

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<double>("HorasEstudadas")
                        .HasColumnType("double");

                    b.Property<double>("MetaHoras")
                        .HasColumnType("double");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Prioridade")
                        .HasColumnType("double");

                    b.Property<string>("Unidade")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("TarefaID");

                    b.ToTable("Tarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
